(define
 (problem pfile_3_010)
 (:domain blocks)
 (:objects arm1 arm2 arm3 - ARM
           b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 - BLOCK)
 (:init
  (hand-empty arm1)
  (hand-empty arm2)
  (hand-empty arm3)
  (clear b4)
  (on-table b10)
  (on b4 b8)
  (on b8 b2)
  (on b2 b7)
  (on b7 b3)
  (on b3 b6)
  (on b6 b10)
  (clear b9)
  (on-table b5)
  (on b9 b1)
  (on b1 b5))
 (:goal (and
         (clear b8)
         (on-table b8)
         (clear b2)
         (on-table b7)
         (on b2 b10)
         (on b10 b1)
         (on b1 b7)
         (clear b6)
         (on-table b3)
         (on b6 b4)
         (on b4 b9)
         (on b9 b5)
         (on b5 b3))))